// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6f1YX4VnaS-FzUmMYpxDqzbTPi1rxAe8',
    appId: '1:117881581095:web:6520de00a54761bf95a802',
    messagingSenderId: '117881581095',
    projectId: 'dfake-a419f',
    authDomain: 'dfake-a419f.firebaseapp.com',
    storageBucket: 'dfake-a419f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOAnNbbYE6CO_vCe49DyDfveJ7biJ3iCM',
    appId: '1:117881581095:android:569d1acc37b878a495a802',
    messagingSenderId: '117881581095',
    projectId: 'dfake-a419f',
    storageBucket: 'dfake-a419f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpJnrq6_gnRcVIvr7h3NbVJcA-9bMhZC4',
    appId: '1:117881581095:ios:9f81404ea758ce5995a802',
    messagingSenderId: '117881581095',
    projectId: 'dfake-a419f',
    storageBucket: 'dfake-a419f.appspot.com',
    iosClientId: '117881581095-hba834hqi6ngdao297siog5cqnlkv32j.apps.googleusercontent.com',
    iosBundleId: 'com.example.dFake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpJnrq6_gnRcVIvr7h3NbVJcA-9bMhZC4',
    appId: '1:117881581095:ios:9f81404ea758ce5995a802',
    messagingSenderId: '117881581095',
    projectId: 'dfake-a419f',
    storageBucket: 'dfake-a419f.appspot.com',
    iosClientId: '117881581095-hba834hqi6ngdao297siog5cqnlkv32j.apps.googleusercontent.com',
    iosBundleId: 'com.example.dFake',
  );
}
